// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GrpcDemo.proto

package com.instructure.bridge.ngilbert.hackweek.demo;

public final class GrpcRestDemo {
  private GrpcRestDemo() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_instructure_bridge_ngilbert_hackweek_MsgRequest_descriptor;
  static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_instructure_bridge_ngilbert_hackweek_MsgRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_instructure_bridge_ngilbert_hackweek_MsgResponse_descriptor;
  static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_instructure_bridge_ngilbert_hackweek_MsgResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\016GrpcDemo.proto\022(com.instructure.bridge" +
      ".ngilbert.hackweek\"\037\n\nMsgRequest\022\021\n\ttime" +
      "stamp\030\001 \001(\003\"1\n\013MsgResponse\022\021\n\ttimestamp\030" +
      "\001 \001(\003\022\017\n\007message\030\002 \001(\t2\201\001\n\013DemoService\022r" +
      "\n\003Msg\0224.com.instructure.bridge.ngilbert." +
      "hackweek.MsgRequest\0325.com.instructure.br" +
      "idge.ngilbert.hackweek.MsgResponseB?\n-co" +
      "m.instructure.bridge.ngilbert.hackweek.d" +
      "emoB\014GrpcRestDemoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_instructure_bridge_ngilbert_hackweek_MsgRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_instructure_bridge_ngilbert_hackweek_MsgRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_instructure_bridge_ngilbert_hackweek_MsgRequest_descriptor,
        new String[] { "Timestamp", });
    internal_static_com_instructure_bridge_ngilbert_hackweek_MsgResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_instructure_bridge_ngilbert_hackweek_MsgResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_instructure_bridge_ngilbert_hackweek_MsgResponse_descriptor,
        new String[] { "Timestamp", "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
