// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GrpcDemo.proto

package com.instructure.bridge.ngilbert.hackweek.demo;

public interface MsgRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.instructure.bridge.ngilbert.hackweek.MsgRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 timestamp = 1;</code>
   */
  long getTimestamp();
}
