// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GrpcDemo.proto

package com.instructure.bridge.ngilbert.hackweek.demo;

public interface MsgResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.instructure.bridge.ngilbert.hackweek.MsgResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 timestamp = 1;</code>
   */
  long getTimestamp();

  /**
   * <code>string message = 2;</code>
   */
  String getMessage();
  /**
   * <code>string message = 2;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
